In [33]:
import pandas as pd
import numpy as np
import os
print(os.getcwd())

/home/alsaibie/Kuwait_HS_Results

In [34]:
#2018
df_2018_STEM_raw = pd.read_csv("sorted_data/2018/2018_STEM_raw.csv")
df_2018_Humanities_raw = pd.read_csv("sorted_data/2018/2018_Humanities_raw.csv")
df_2018_STEM_raw.head(10)

,النسبة,النجاح,علمي,المدرسة,حكومي/خاص,المنطقة التعليمية,الجنس,الجنسية,الإسم بالكامل,رقم الجلوس,الرقم المدني
0,66.29,ناجح,العلمي,يوسف بن عيسى الثانوية للبنين,حكــومى,العاصمة,بنين,كويتي,أحمد سعود عبد العزيز الرميح,40001,300062700613
1,93.92,ناجح,العلمي,يوسف بن عيسى الثانوية للبنين,حكــومى,العاصمة,بنين,كويتي,أحمد عبد المحسن عبد الله العوده,40002,300082700637
2,80.09,ناجح,العلمي,يوسف بن عيسى الثانوية للبنين,حكــومى,العاصمة,بنين,كويتي,احمد سعد احمد العبيد,40003,300102801495
3,85.89,ناجح,العلمي,يوسف بن عيسى الثانوية للبنين,حكــومى,العاصمة,بنين,كويتي,خالد أحمد غانم المطر,40005,300120200183
4,86.68,ناجح,العلمي,يوسف بن عيسى الثانوية للبنين,حكــومى,العاصمة,بنين,كويتي,خالد حمد أحمد حمد حسين المراغي,40006,300021601053
5,94.06,ناجح,العلمي,يوسف بن عيسى الثانوية للبنين,حكــومى,العاصمة,بنين,كويتي,خالد عبد الله محمد الشراح,40007,301020700353
6,73.95,ناجح,العلمي,يوسف بن عيسى الثانوية للبنين,حكــومى,العاصمة,بنين,كويتي,خالد محمد عبد الباري العليان,40008,300110100103
7,87.40,ناجح,العلمي,يوسف بن عيسى الثانوية للبنين,حكــومى,العاصمة,بنين,كويتي,سالم عادل سالم العبدلى,40009,300061901202
8,91.76,ناجح,العلمي,يوسف بن عيسى الثانوية للبنين,حكــومى,العاصمة,بنين,يمني,سالم عبد الرحمن سالم البكر,40010,301021900429
9,86.90,ناجح,العلمي,يوسف بن عيسى الثانوية للبنين,حكــومى,العاصمة,بنين,كويتي,سعود رائد دخيل الحميدان,40011,300082200296

In [55]:
# df_2018_STEM_raw.drop(df_2018_STEM_raw.columns[[]])
df_2018_STEM_fliplr = df_2018_STEM_raw[df_2018_STEM_raw.columns[::-1]]
df_2018_STEM_clean = df_2018_STEM_fliplr.drop(df_2018_STEM_fliplr.columns[[0, 1, 2, 8, 9]], axis=1)

df_2018_Humanities_fliplr = df_2018_Humanities_raw[df_2018_Humanities_raw.columns[::-1]]
df_2018_Humanities_clean = df_2018_Humanities_fliplr.drop(df_2018_STEM_fliplr.columns[[0, 1, 2]], axis=1)

display(df_2018_STEM_clean.head())
display(df_2018_STEM_clean.head())

df_2018_STEM_clean.to_csv("sorted_data/2018/2018_STEM_clean.csv", sep=",")
df_2018_Humanities_clean.to_csv("sorted_data/2018/2018_Humanities_clean.csv", sep=",")

,الجنسية,الجنس,المنطقة التعليمية,حكومي/خاص,المدرسة,النسبة
0,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,66.29
1,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,93.92
2,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,80.09
3,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,85.89
4,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,86.68

,الجنسية,الجنس,المنطقة التعليمية,حكومي/خاص,المدرسة,النسبة
0,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,66.29
1,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,93.92
2,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,80.09
3,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,85.89
4,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,86.68

In [69]:
#2017
df_2017_Humanities_raw = pd.read_csv("sorted_data/2017/2017_Humanities_raw.csv")
display(df_2017_Humanities_raw.head())

df_2017_STEM_raw = pd.read_csv("sorted_data/2017/2017_STEM_raw.csv")
display(df_2017_STEM_raw.head())

,النسبة,النجاح,المدرسة,حكومي/خاص,المنطقة التعليمية,الجنس,الجنسية,الإسم بالكامل,رقم الجلوس
0,76.07,ناجح,يوسف بن عيسى الثانوية للبنين,حكــومى,العاصمة,بنين,كويتي,أيوب خالد أيوب الخميس,11
1,87.64,ناجح,يوسف بن عيسى الثانوية للبنين,حكــومى,العاصمة,بنين,كويتي,بدر ناصر بدر اللافى,12
2,65.24,ناجح,يوسف بن عيسى الثانوية للبنين,حكــومى,العاصمة,بنين,كويتي,جاسم باسل جاسم الحجى,13
3,NaN,لديه دور ثانى,يوسف بن عيسى الثانوية للبنين,حكــومى,العاصمة,بنين,كويتي,جاسم حسن عبد الرسول الشواف,14
4,75.95,ناجح,يوسف بن عيسى الثانوية للبنين,حكــومى,العاصمة,بنين,كويتي,حسن علي عبد الله جمال,15

,النسبة,المدرسة,حكومي/خاص,المنطقة التعليمية,الجنس,الجنسية,الإسم بالكامل,رقم الجلوس
0,76.44,يوسف بن عيسى الثانوية للبنين,حكــومى,العاصمة,بنين,كويتي,ابراهيم جمال ابراهيم الراشد,30002
1,91.18,يوسف بن عيسى الثانوية للبنين,حكــومى,العاصمة,بنين,كويتي,احمد اسامه احمد السنين,30003
2,84.74,يوسف بن عيسى الثانوية للبنين,حكــومى,العاصمة,بنين,كويتي,احمد طارق احمد العوض,30004
3,90.12,يوسف بن عيسى الثانوية للبنين,حكــومى,العاصمة,بنين,كويتي,احمد منصور راشد الرشدان,30005
4,95.61,يوسف بن عيسى الثانوية للبنين,حكــومى,العاصمة,بنين,كويتي,بدر فؤاد نصف العصفور,30006

In [77]:
df_2017_STEM_fliplr = df_2017_STEM_raw[df_2017_STEM_raw.columns[::-1]]
df_2017_STEM_clean = df_2017_STEM_fliplr.drop(df_2017_STEM_fliplr.columns[[0,1]], axis=1)

df_2017_Humanities_fliplr = df_2017_Humanities_raw[df_2017_Humanities_raw.columns[::-1]]
df_2017_Humanities_clean = df_2017_Humanities_fliplr.drop(df_2017_Humanities_fliplr.columns[[0,1, 7]], axis=1)
df_2017_Humanities_clean = df_2017_Humanities_clean[np.isfinite(df_2017_Humanities_clean[u'النسبة'])]

display(df_2017_STEM_clean.head())
display(df_2017_Humanities_clean.head())

df_2017_STEM_clean.to_csv("sorted_data/2017/2017_STEM_clean.csv", sep=",")
df_2017_Humanities_clean.to_csv("sorted_data/2017/2017_Humanities_clean.csv", sep=",")

,الجنسية,الجنس,المنطقة التعليمية,حكومي/خاص,المدرسة,النسبة
0,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,76.44
1,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,91.18
2,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,84.74
3,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,90.12
4,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,95.61

,الجنسية,الجنس,المنطقة التعليمية,حكومي/خاص,المدرسة,النسبة
0,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,76.07
1,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,87.64
2,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,65.24
4,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,75.95
6,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,73.85

In [72]:
#2016
df_2016_Humanities_raw = pd.read_csv("sorted_data/2016/2016_Humanities_raw.csv")
display(df_2016_Humanities_raw.head())

df_2016_STEM_raw = pd.read_csv("sorted_data/2016/2016_STEM_raw.csv")
display(df_2016_STEM_raw.head())

,الرقم المدني,رقم الجلوس,الإسم بالكامل,الجنسية,الجنس,المنطقة التعليمية,حكومي/خاص,المدرسة,النسبة
0,298091200909,11,أحمد أنور أحمد البنوان,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,87.95
1,298011500443,12,أحمد عدنان عبدالرضا البنا,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,73.54
2,299012000269,14,حمد محمد سعود الدوسري,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,74.03
3,298061200756,15,خالد وضاح خالد الزيد,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,69.57
4,298080400323,16,سعد فهد صالح الخنه,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,74.82

,الرقم المدني,رقم الجلوس,الإسم بالكامل,الجنسية,الجنس,المنطقة التعليمية,حكومي/خاص,المدرسة,النسبة
0,298122900626,30001,أحمد خالد سليمان بوكحيل,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,74.77
1,,30002,أحمد عبدالهادي أحمد عبدالرضا,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,71.05
2,298092900982,30003,أحمد مساعد عبد العزيز البسام,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,70.82
3,298071900377,30004,ابراهيم احمد شاهين الشملان,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,94.29
4,298123000136,30005,احمد انور احمد اليتامى,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,77.45

In [76]:
df_2016_STEM_clean = df_2016_STEM_raw.drop(df_2016_STEM_raw.columns[[0,1,2]], axis=1)
df_2016_Humanities_clean = df_2016_Humanities_raw.drop(df_2016_Humanities_raw.columns[[0,1,2]], axis=1)

display(df_2016_STEM_clean.head())
display(df_2016_Humanities_clean.head())

df_2016_STEM_clean.to_csv("sorted_data/2016/2016_STEM_clean.csv", sep=",")
df_2016_Humanities_clean.to_csv("sorted_data/2016/2016_Humanities_clean.csv", sep=",")

,الجنسية,الجنس,المنطقة التعليمية,حكومي/خاص,المدرسة,النسبة
0,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,74.77
1,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,71.05
2,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,70.82
3,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,94.29
4,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,77.45

,الجنسية,الجنس,المنطقة التعليمية,حكومي/خاص,المدرسة,النسبة
0,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,87.95
1,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,73.54
2,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,74.03
3,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,69.57
4,كويتي,بنين,العاصمة,حكــومى,يوسف بن عيسى الثانوية للبنين,74.82